services:
  db:
    container_name: "footballdb"
    image: postgres:17.5-bookworm
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "rootpassword"
      POSTGRES_DB: "football"
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
volumes:
  pgdata: 
