//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "enum")]
pub enum Enum {
    #[sea_orm(string_value = "First Tier")]
    FirstTier,
    #[sea_orm(string_value = "Second Tier")]
    SecondTier,
    #[sea_orm(string_value = "Third Tier")]
    ThirdTier,
    #[sea_orm(string_value = "Fourth Tier")]
    FourthTier,
    #[sea_orm(string_value = "Fifth Tier")]
    FifthTier,
    #[sea_orm(string_value = "Sixth Tier")]
    SixthTier,
    #[sea_orm(string_value = "Youth League")]
    YouthLeague,
    #[sea_orm(string_value = "Domestic Cup")]
    DomesticCup,
    #[sea_orm(string_value = "Domestic Super Cup")]
    DomesticSuperCup,
    #[sea_orm(string_value = "Play-Offs")]
    PlayOffs,
    #[sea_orm(string_value = "League Cup")]
    LeagueCup,
    #[sea_orm(string_value = "Domestic Youth Cup")]
    DomesticYouthCup,
    #[sea_orm(string_value = "Reserve league")]
    ReserveLeague,
    #[sea_orm(string_value = "Further Cup")]
    FurtherCup,
    #[sea_orm(string_value = "National Youth Super Cup")]
    NationalYouthSuperCup,
    #[sea_orm(string_value = "International Cups")]
    InternationalCups,
    #[sea_orm(string_value = "Cups")]
    Cups,
}
